package com.lazytop.transtest.domain;

public class PhoneNumberBelong {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_number_belong.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_number_belong.segment
     *
     * @mbggenerated
     */
    private Integer segment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_number_belong.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_number_belong.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_number_belong.id
     *
     * @return the value of phone_number_belong.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_number_belong.id
     *
     * @param id the value for phone_number_belong.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_number_belong.segment
     *
     * @return the value of phone_number_belong.segment
     *
     * @mbggenerated
     */
    public Integer getSegment() {
        return segment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_number_belong.segment
     *
     * @param segment the value for phone_number_belong.segment
     *
     * @mbggenerated
     */
    public void setSegment(Integer segment) {
        this.segment = segment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_number_belong.aid
     *
     * @return the value of phone_number_belong.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_number_belong.aid
     *
     * @param aid the value for phone_number_belong.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_number_belong.area
     *
     * @return the value of phone_number_belong.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_number_belong.area
     *
     * @param area the value for phone_number_belong.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area;
    }
}