package com.lazytop.transtest.mappers;

import com.lazytop.transtest.domain.PhoneNumberBelong;

public interface PhoneNumberBelongMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_number_belong
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_number_belong
     *
     * @mbggenerated
     */
    int insert(PhoneNumberBelong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_number_belong
     *
     * @mbggenerated
     */
    int insertSelective(PhoneNumberBelong record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_number_belong
     *
     * @mbggenerated
     */
    PhoneNumberBelong selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_number_belong
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhoneNumberBelong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_number_belong
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhoneNumberBelong record);
}