package com.lazytop.transtest.mappers;

import com.lazytop.transtest.domain.SysRegion;
import com.lazytop.transtest.domain.SysRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int countByExample(SysRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int deleteByExample(SysRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int insert(SysRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int insertSelective(SysRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    List<SysRegion> selectByExample(SysRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    SysRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRegion record, @Param("example") SysRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRegion record, @Param("example") SysRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRegion record);
}